/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quiz;

import java.io.*;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author ariya
 */
public class main extends javax.swing.JFrame {

    int harga,harga_tiket;
    
    public void tiket(){
        comb_tiket.removeAllItems();
        comb_tiket.addItem("Jumlah Tiket");
        for(int i=1; i<=10;i++){
            comb_tiket.addItem(String.valueOf(i));
        }        
    }
    
    public void st_sa(){
        comb_sa.removeAllItems();
        comb_sa.addItem("Stasiun Awal");
        comb_sa.addItem("Jakarta");
        comb_sa.addItem("Bekasi");
        comb_sa.addItem("Bandung");
    }
    public void st_st(){
        comb_st.removeAllItems();
        comb_st.addItem("Stasiun Tujuan");
        comb_st.addItem("Yogyakarta");
        comb_st.addItem("Semarang");
        comb_st.addItem("Madiun");
    }
    
    public int cek(String asal,String tujuan){
        if(asal.equalsIgnoreCase("Jakarta") && tujuan.equalsIgnoreCase("Yogyakarta")){
            harga = 300000;
        }
        else if(asal.equalsIgnoreCase("Bekasi") && tujuan.equalsIgnoreCase("Yogyakarta")){
            harga = 250000;
        }
        else if(asal.equalsIgnoreCase("Bandung") && tujuan.equalsIgnoreCase("Yogyakarta")){
            harga = 200000;
        }
        
        else if(asal.equalsIgnoreCase("Jakarta") && tujuan.equalsIgnoreCase("Semarang")){
            harga = 320000;
        }
        else if(asal.equalsIgnoreCase("Bekasi") && tujuan.equalsIgnoreCase("Semarang")){
            harga = 280000;
        }
        else if(asal.equalsIgnoreCase("Bandung") && tujuan.equalsIgnoreCase("Semarang")){
            harga = 250000;
        }
        
        else if(asal.equalsIgnoreCase("Jakarta") && tujuan.equalsIgnoreCase("Madiun")){
            harga = 400000;
        }
        else if(asal.equalsIgnoreCase("Bekasi") && tujuan.equalsIgnoreCase("Madiun")){
            harga = 350000;
        }
        else if(asal.equalsIgnoreCase("Bandung") && tujuan.equalsIgnoreCase("Madiun")){
            harga = 300000;
        }
        return harga;
    }
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        tiket();
        st_sa();
        st_st();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        inp_ktp = new javax.swing.JTextField();
        inp_nama = new javax.swing.JTextField();
        comb_sa = new javax.swing.JComboBox<>();
        comb_st = new javax.swing.JComboBox<>();
        comb_tiket = new javax.swing.JComboBox<>();
        total = new javax.swing.JTextField();
        bt_proses = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        view_cek = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inp_ktp.setText("Masukan KTP");
        inp_ktp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inp_ktpMouseClicked(evt);
            }
        });
        jPanel2.add(inp_ktp, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 66, 240, -1));

        inp_nama.setText("Masukan Nama");
        inp_nama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inp_namaMouseClicked(evt);
            }
        });
        jPanel2.add(inp_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 113, 240, -1));

        comb_sa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3 ", "Item 4", " " }));
        jPanel2.add(comb_sa, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 160, 150, -1));

        comb_st.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4", " " }));
        jPanel2.add(comb_st, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 207, 150, -1));

        comb_tiket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comb_tiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_tiketActionPerformed(evt);
            }
        });
        jPanel2.add(comb_tiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 248, 150, -1));

        total.setText("0");
        jPanel2.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 240, -1));

        bt_proses.setText("Proses");
        bt_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_prosesActionPerformed(evt);
            }
        });
        jPanel2.add(bt_proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel1.setText("Harga Tiket");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 30));

        jLabel2.setText("Nomor KTP");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 30));

        jLabel3.setText("Nama");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        jLabel4.setText("Stasiun Awal");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        jLabel5.setText("Stasiun Tujuan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        jLabel6.setText("Jumlah Tiket");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        jTabbedPane1.addTab("tiket", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        view_cek.setColumns(20);
        view_cek.setRows(5);
        jScrollPane1.setViewportView(view_cek);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 480, 350));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("cek");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 70, -1));

        jTabbedPane1.addTab("cek", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 500, 450));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setText("YukPergi.com");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inp_ktpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inp_ktpMouseClicked
        // TODO add your handling code here:
        inp_ktp.setText("");
    }//GEN-LAST:event_inp_ktpMouseClicked

    private void inp_namaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inp_namaMouseClicked
        // TODO add your handling code here:
        inp_nama.setText("");
    }//GEN-LAST:event_inp_namaMouseClicked

    private void bt_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_prosesActionPerformed
        // TODO add your handling code here:
        String path = "C:\\Users\\ariya\\OneDrive\\Desktop\\tiket.txt";
        
        try{
            FileWriter save = new FileWriter(path);
            save.write("Nama \t: " + inp_nama.getText() +"\n"+
                       "No. KTP \t: " + inp_ktp.getText() +"\n"+
                       "Stasiun Awal \t: " + comb_sa.getSelectedItem() +"\n"+
                       "Stasiun Tujuan \t: " + comb_st.getSelectedItem() +"\n"+
                       "Jumlah Tiket \t: " + comb_tiket.getSelectedItem() +"\n"+
                       "Total Bayar \t: " + total.getText() +"\n");
            save.close();
            JOptionPane.showMessageDialog(null, "Berhasil di simpan di " + path);
        } catch(IOException e){
            JOptionPane.showMessageDialog(null, "Error");
        }
        
    }//GEN-LAST:event_bt_prosesActionPerformed

    private void comb_tiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_tiketActionPerformed
        // TODO add your handling code here:
        int cek_harga = cek(String.valueOf(comb_sa.getSelectedItem()),String.valueOf(comb_st.getSelectedItem()));
        harga_tiket = comb_tiket.getSelectedIndex() * cek_harga;
        
        total.setText(String.valueOf(harga_tiket));
    }//GEN-LAST:event_comb_tiketActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String path = "C:\\Users\\ariya\\OneDrive\\Desktop\\tiket.txt";
        try{
            view_cek.setText("");
            File masuk = new File(path);
            Scanner reader = new Scanner(masuk);
            while(reader.hasNextLine()){
                String data = reader.nextLine();
                view_cek.append(data+"\n");
            }
            reader.close();
        } catch (IOException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
    
        
        
 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_proses;
    private javax.swing.JComboBox<String> comb_sa;
    private javax.swing.JComboBox<String> comb_st;
    public javax.swing.JComboBox<String> comb_tiket;
    public javax.swing.JTextField inp_ktp;
    public javax.swing.JTextField inp_nama;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField total;
    private javax.swing.JTextArea view_cek;
    // End of variables declaration//GEN-END:variables
}
