/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import controller.koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author ariya
 */
public class employee_gui extends javax.swing.JFrame {

    
    koneksi con = new koneksi();
    ResultSet rs;
    int DeptId;
    String birth,empId;
    DefaultTableModel dt;
    
    /**
     * Creates new form dept_form
     */
    public employee_gui() {
        initComponents();        
        addDept(cb_dept);
        removeTable(tabel_show_emp);
        displayTable();
        AutoCompleteDecorator.decorate(cb_dept);
        initMethod();
    }

    class Item {

        private int id;
        private String description;

        public Item(int id, String description) {
            this.id = id;
            this.description = description;
        }

        public int getId() {
            return id;
        }

        public String toString() {
            return description;
        }
    }
    
    public void addDept(JComboBox cmb) {

        cmb.removeAllItems();
        try {
            cmb.removeAllItems();
            cmb.addItem("-- Pilih Dept --");
            String query = "SELECT * FROM departement";
            rs = con.lihatData(query);
            while (rs.next()) {
                String Txtcmb = rs.getString("deptcode").trim();
                int idCmb = rs.getInt("id");
                Item comboItem = new Item(idCmb, Txtcmb);
                cmb.addItem(comboItem);
            }
        } catch (Exception e) {
            System.out.println("Error " + e);
        }
    }
    
    void initMethod() {
        cb_dept.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent arg0) {
                JComboBox jc = (JComboBox) arg0.getSource();
                Item item = (Item) jc.getSelectedItem();
                DeptId = item.getId();
            }
        });
    }
    
    void removeTable(JTable jt) {

        dt = (DefaultTableModel) tabel_show_emp.getModel();
        int rowCount = dt.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            dt.removeRow(0);
        }
    }
    
    void displayTable() {

        removeTable(tabel_show_emp);
        String sql = "SELECT e.id, e.employee_id,e.nama,e.alamat,e.tempat_lahir,"
                + "e.tanggal_lahir,d.deptcode\n"
                + "FROM employees e\n"
                + "INNER JOIN departement d\n"
                + "on e.dept_id=d.id;";
        System.out.println("SQL : " + sql);
        rs = con.lihatData(sql);
        DefaultTableModel dt = (DefaultTableModel) tabel_show_emp.getModel();
        Object rows[];
        try {
            while (rs.next()) {
                int id = Integer.parseInt(rs.getString("id"));
                String empId = rs.getString("employee_id");
                String fullName = rs.getString("nama");
                String alamat = rs.getString("alamat");
                String tempatLahir = rs.getString("tempat_lahir");
                String birth = rs.getString("tanggal_lahir");
                String deptname = rs.getString("deptcode");
                
                rows = new Object[]{id, empId, fullName, alamat, tempatLahir, birth, deptname};
                dt.addRow(rows);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }

    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inp_emid = new javax.swing.JTextField();
        inp_nama = new javax.swing.JTextField();
        inp_tmp = new javax.swing.JTextField();
        inp_tgl = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        inp_alamat = new javax.swing.JTextArea();
        bt_search = new javax.swing.JButton();
        bt_insert = new javax.swing.JButton();
        bt_update = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel_show_emp = new javax.swing.JTable();
        cb_dept = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel1.setText("Alamat");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("Employee Form");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel3.setText("Employee-ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Nama");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 30));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel5.setText("Tempat Lahir");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Tanggal Lahir");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("Departement");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 30));
        jPanel1.add(inp_emid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 400, -1));
        jPanel1.add(inp_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 400, -1));
        jPanel1.add(inp_tmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 400, -1));
        jPanel1.add(inp_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 400, -1));

        inp_alamat.setColumns(20);
        inp_alamat.setRows(5);
        jScrollPane1.setViewportView(inp_alamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 400, 110));

        bt_search.setText("Search");
        jPanel1.add(bt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, 90, -1));

        bt_insert.setText("Insert");
        bt_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_insertActionPerformed(evt);
            }
        });
        jPanel1.add(bt_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 80, -1));

        bt_update.setText("Update");
        jPanel1.add(bt_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 90, -1));

        bt_delete.setText("Delete");
        jPanel1.add(bt_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 90, -1));

        tabel_show_emp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Em. ID", "Nama", "Alamat", "Tmo, Lahir", "Tgl Lahir", "Dept. Kode"
            }
        ));
        tabel_show_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_show_empMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel_show_emp);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 540, 230));

        cb_dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cb_dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 400, -1));

        jMenu1.setText("Departement");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Employee");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabel_show_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_show_empMouseClicked
        // TODO add your handling code here:
        displayTable();
        try {
            dt = (DefaultTableModel) jTable1.getModel();
            int rowId = jTable1.getSelectedRow();
            empId = dt.getValueAt(rowId, 0).toString();
            String sql = "SELECT e.id, e.employee_id,e.nama,e.alamat,e.tempat_lahir,e.tanggal_lahir,d.id deptid,d.deptcode\n"
                    + "FROM employees e\n"
                    + "INNER JOIN departement d\n"
                    + "on e.dept_id=d.id"
                    + " WHERE e.id=" + empId;
            System.out.println("SQL : " + sql);
            rs = con.lihatData(sql);
            while (rs.next()) {
                inp_emid.setText(rs.getString("employee_id"));
                inp_nama.setText(rs.getString("nama"));
                inp_tmp.setText(rs.getString("tempat_lahir"));
                inp_alamat.setText(rs.getString("alamat"));
                Date date = (Date) new SimpleDateFormat("yyyy-MM-dd").parse((String) rs.getString("tanggal_lahir"));
                System.out.println("Date : " + date);
                inp_tgl.setDate(date);
                String Txtcmb = rs.getString("deptcode").trim();
                int idCmb = rs.getInt("deptid");
                Item comboItem = new Item(idCmb, Txtcmb);
                cb_dept.setSelectedItem(comboItem);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }
    }//GEN-LAST:event_tabel_show_empMouseClicked

    private void bt_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_insertActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            birth = dateFormat.format(inp_tgl.getDate());
            String sql = "insert into employees(employee_id,nama,tempat_lahir,tanggal_lahir,alamat,dept_id)"
                    + "VALUES ('" + inp_emid.getText() + "','" + inp_nama.getText() + "','" + inp_tmp.getText() + "' "
                    + ",STR_TO_DATE('" + birth + "','%d-%m-%Y'),'" + inp_alamat.getText() + "'," + DeptId + ")";

            System.out.println("SQL : " + sql);
            con.dmlData(sql);
            displayTable();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :" + e);
        }
    }//GEN-LAST:event_bt_insertActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        new departement_form().setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        new employee_gui().setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_insert;
    private javax.swing.JButton bt_search;
    private javax.swing.JButton bt_update;
    private javax.swing.JComboBox<String> cb_dept;
    private javax.swing.JTextArea inp_alamat;
    private javax.swing.JTextField inp_emid;
    private javax.swing.JTextField inp_nama;
    private com.toedter.calendar.JDateChooser inp_tgl;
    private javax.swing.JTextField inp_tmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabel_show_emp;
    // End of variables declaration//GEN-END:variables
}
