/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import controller.koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariya
 */
public class cari_kode_peminjaman extends javax.swing.JDialog {

    /**
     * Creates new form cari_kode_peminjaman
     */
    koneksi con = new koneksi();
    ResultSet rs;
    Statement stmt;
    String kode_peminjaman, tanggal_pinjam;

    public String AmbilText() {
        return kode_peminjaman;
    }
    void removeTable(JTable jt) {
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        int rowCount = dt.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            dt.removeRow(0);
        }
    }

    void displayTable() {
        removeTable(tabel_cari_kode);
        DefaultTableModel dt = (DefaultTableModel) tabel_cari_kode.getModel();

        String query = "SELECT p.kode_peminjaman,b.judul_buku,a.nama_anggota,p.tanggal_kembali FROM data_peminjaman p JOIN data_buku b ON p.kode_buku = b.kode_buku JOIN data_anggota a ON p.kode_anggota = a.kode_anggota;";
        rs = con.lihatData(query);
        try {
            while (rs.next()) {
                String kode_peminjaman = rs.getString("kode_peminjaman");
                String judul_buku = rs.getString("judul_buku");
                String nama_anggota = rs.getString("nama_anggota");
                String tanggal_pinjam = rs.getString("tanggal_kembali");

                Object[] rows = new Object[]{kode_peminjaman, judul_buku, nama_anggota, tanggal_pinjam};
                dt.addRow(rows);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error : "+ e);
        }
    }

    public cari_kode_peminjaman(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        removeTable(tabel_cari_kode);
        displayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_cari_kode = new javax.swing.JTable();
        bt_batal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("List Peminjaman");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabel_cari_kode.setAutoCreateRowSorter(true);
        tabel_cari_kode.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode peminjaman", "Judul Buku", "Nama Anggota", "Tanggal Kembali"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_cari_kode.setFocusable(false);
        tabel_cari_kode.setGridColor(new java.awt.Color(120, 120, 120));
        tabel_cari_kode.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabel_cari_kode.setShowGrid(true);
        tabel_cari_kode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_cari_kodeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_cari_kode);
        if (tabel_cari_kode.getColumnModel().getColumnCount() > 0) {
            tabel_cari_kode.getColumnModel().getColumn(0).setResizable(false);
            tabel_cari_kode.getColumnModel().getColumn(1).setResizable(false);
            tabel_cari_kode.getColumnModel().getColumn(2).setResizable(false);
            tabel_cari_kode.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, 200));

        bt_batal.setBackground(new java.awt.Color(255, 255, 255));
        bt_batal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(120, 120, 120)));
        bt_batal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_batalMouseClicked(evt);
            }
        });
        bt_batal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Batal");
        bt_batal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 20));

        jPanel1.add(bt_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_batalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_batalMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_bt_batalMouseClicked

    private void tabel_cari_kodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_cari_kodeMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabel_cari_kode.getModel();
        int selectedRow = tabel_cari_kode.getSelectedRow();
        String x = model.getValueAt(selectedRow, 0).toString();

        String sql = "SELECT p.kode_peminjaman,b.judul_buku,a.nama_anggota,p.tanggal_pinjam FROM data_peminjaman p JOIN data_buku b ON p.kode_buku = b.kode_buku JOIN data_anggota a ON p.kode_anggota = a.kode_anggota WHERE kode_peminjaman='"+x+"';";

        rs = con.lihatData(sql);
        try {
            while (rs.next()) {
                kode_peminjaman = rs.getString("kode_peminjaman");
                tanggal_pinjam = rs.getString("tanggal_pinjam");
            }
        } catch (SQLException ex) {
            Logger.getLogger(cari_kode_peminjaman.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabel_cari_kodeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cari_kode_peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cari_kode_peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cari_kode_peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cari_kode_peminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cari_kode_peminjaman dialog = new cari_kode_peminjaman(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bt_batal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_cari_kode;
    // End of variables declaration//GEN-END:variables
}
