/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

/**
 *
 * @author ariya
 */
public class dashboard extends javax.swing.JFrame {

    

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
//        panel_table.show();
//        panel_input.hide();
//        panel_buku.hide();
        
        
//        tabel_dashboard.getTableHeader().setFont(new Font("Segeou UI",Font.PLAIN, 14));

//        tabel_dashboard.getTableHeader().setBackground(new Color(102,102,102));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        image_logo = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        bt_log = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        bt_dashboard = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        bt_inp_pinjam = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        bt_inp_buku = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panel_header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_dashboard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perpustakaan STMIK BANI SALEH");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_menu.setBackground(new java.awt.Color(102, 102, 102));
        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Dashboard");
        panel_menu.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        image_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo_kecil.png"))); // NOI18N
        panel_menu.add(image_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 270, 140));

        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        panel_menu.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, -1, -1));

        role.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        role.setForeground(new java.awt.Color(255, 255, 255));
        role.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        role.setText("Jabatan");
        panel_menu.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, -1));

        username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Nama Pengguna");
        panel_menu.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 220, 270, -1));

        bt_log.setBackground(new java.awt.Color(102, 102, 102));
        bt_log.setForeground(new java.awt.Color(255, 255, 255));
        bt_log.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Log");
        bt_log.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panel_menu.add(bt_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 250, 40));

        bt_dashboard.setBackground(new java.awt.Color(102, 102, 102));
        bt_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        bt_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_dashboardMouseClicked(evt);
            }
        });
        bt_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Dashboard");
        bt_dashboard.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panel_menu.add(bt_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 250, 40));

        bt_inp_pinjam.setBackground(new java.awt.Color(102, 102, 102));
        bt_inp_pinjam.setForeground(new java.awt.Color(255, 255, 255));
        bt_inp_pinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_inp_pinjamMouseClicked(evt);
            }
        });
        bt_inp_pinjam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Input Peminjaman");
        bt_inp_pinjam.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panel_menu.add(bt_inp_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 250, 40));

        bt_inp_buku.setBackground(new java.awt.Color(102, 102, 102));
        bt_inp_buku.setForeground(new java.awt.Color(255, 255, 255));
        bt_inp_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_inp_bukuMouseClicked(evt);
            }
        });
        bt_inp_buku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Input Data Buku");
        bt_inp_buku.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panel_menu.add(bt_inp_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 250, 40));

        jPanel1.add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 660));

        panel_header.setBackground(new java.awt.Color(102, 102, 102));
        panel_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_x_20px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panel_header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PERPUSTAKAAN");
        panel_header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 830, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STMIK BANI SALEH");
        panel_header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 830, -1));

        jPanel1.add(panel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 820, 200));

        panel_dashboard.setBackground(new java.awt.Color(255, 255, 255));
        panel_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_people_30px.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panel_dashboard.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 50));

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_outbox_30px.png"))); // NOI18N
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panel_dashboard.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 180, 50));

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_book_30px.png"))); // NOI18N
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panel_dashboard.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 180, 50));

        jPanel1.add(panel_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 800, 420));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 800, 420));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 800, 420));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 800, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void bt_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_dashboardMouseClicked
        // TODO add your handling code here:
//        panel_table.show();
//        panel_input.hide();
//        panel_buku.hide();
    }//GEN-LAST:event_bt_dashboardMouseClicked

    private void bt_inp_pinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_inp_pinjamMouseClicked
        // TODO add your handling code here:
//        panel_table.hide();
//        panel_input.show();
//        panel_buku.hide();
    }//GEN-LAST:event_bt_inp_pinjamMouseClicked

    private void bt_inp_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_inp_bukuMouseClicked
        // TODO add your handling code here:
//        panel_table.hide();
//        panel_input.hide();
//        panel_buku.show();
    }//GEN-LAST:event_bt_inp_bukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bt_dashboard;
    private javax.swing.JPanel bt_inp_buku;
    private javax.swing.JPanel bt_inp_pinjam;
    private javax.swing.JPanel bt_log;
    private javax.swing.JLabel image_logo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel panel_dashboard;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JLabel role;
    private javax.swing.JLabel title;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
