/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.*;

/**
 *
 * @author ariya
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        panel_table.show();
        panel_input.hide();
        panel_buku.hide();
        
        
        tabel_dashboard.getTableHeader().setFont(new Font("Segeou UI",Font.PLAIN, 14));

//        tabel_dashboard.getTableHeader().setBackground(new Color(102,102,102));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        image_logo = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        role = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        bt_log = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        bt_dashboard = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        bt_inp_pinjam = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        bt_inp_buku = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panel_header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel_table = new javax.swing.JPanel();
        tabelScroll_1 = new javax.swing.JScrollPane();
        tabel_dashboard = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        panel_input = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panel_buku = new javax.swing.JPanel();
        tabelScroll_2 = new javax.swing.JScrollPane();
        tabel_dashboard1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Perpustakaan STMIK BANI SALEH");
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_menu.setBackground(new java.awt.Color(102, 102, 102));
        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Dashboard");
        panel_menu.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        image_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo_kecil.png"))); // NOI18N
        panel_menu.add(image_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 270, 140));

        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        panel_menu.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, -1, -1));

        role.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        role.setForeground(new java.awt.Color(255, 255, 255));
        role.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        role.setText("Jabatan");
        panel_menu.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, -1));

        username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("Nama Pengguna");
        panel_menu.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 220, 270, -1));

        bt_log.setBackground(new java.awt.Color(102, 102, 102));
        bt_log.setForeground(new java.awt.Color(255, 255, 255));
        bt_log.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Log");
        bt_log.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panel_menu.add(bt_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 250, 40));

        bt_dashboard.setBackground(new java.awt.Color(102, 102, 102));
        bt_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        bt_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_dashboardMouseClicked(evt);
            }
        });
        bt_dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Dashboard");
        bt_dashboard.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panel_menu.add(bt_dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 250, 40));

        bt_inp_pinjam.setBackground(new java.awt.Color(102, 102, 102));
        bt_inp_pinjam.setForeground(new java.awt.Color(255, 255, 255));
        bt_inp_pinjam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_inp_pinjamMouseClicked(evt);
            }
        });
        bt_inp_pinjam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Input Peminjaman");
        bt_inp_pinjam.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panel_menu.add(bt_inp_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 250, 40));

        bt_inp_buku.setBackground(new java.awt.Color(102, 102, 102));
        bt_inp_buku.setForeground(new java.awt.Color(255, 255, 255));
        bt_inp_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_inp_bukuMouseClicked(evt);
            }
        });
        bt_inp_buku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Input Data Buku");
        bt_inp_buku.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        panel_menu.add(bt_inp_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 250, 40));

        jPanel1.add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 660));

        panel_header.setBackground(new java.awt.Color(102, 102, 102));
        panel_header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_x_20px.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panel_header.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PERPUSTAKAAN");
        panel_header.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 830, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("STMIK BANI SALEH");
        panel_header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 830, -1));

        jPanel1.add(panel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 820, 200));

        panel_table.setBackground(new java.awt.Color(255, 255, 255));
        panel_table.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelScroll_1.setBackground(new java.awt.Color(255, 255, 255));
        tabelScroll_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tabelScroll_1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tabelScroll_1.setColumnHeaderView(null);
        tabelScroll_1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelScroll_1.setFocusable(false);

        tabel_dashboard.setAutoCreateRowSorter(true);
        tabel_dashboard.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tabel_dashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "43A87006200xxx", "Aulia", "Python", "19-07-2022", "26-07-2022", null},
                {"2", "43A87006200xxx", "Abel", "Java", "19-07-2022", "26-07-2022", "Sudah Kembali"},
                {"3", "43A87006200xxx", "Dwi", "CSS", "19-07-2022", "26-07-2022", null},
                {"4", "43A87006200xxx", "Azaria", "PHP", "19-07-2022", "26-07-2022", null}
            },
            new String [] {
                "No", "NPM", "Nama", "Buku", "Tgl Pinjam", "Tgl Kembali", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_dashboard.setFocusable(false);
        tabel_dashboard.setGridColor(new java.awt.Color(255, 255, 255));
        tabel_dashboard.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabel_dashboard.setOpaque(false);
        tabel_dashboard.setPreferredSize(new java.awt.Dimension(400, 100));
        tabel_dashboard.setRowHeight(25);
        tabel_dashboard.setShowGrid(false);
        tabel_dashboard.getTableHeader().setReorderingAllowed(false);
        tabel_dashboard.setUpdateSelectionOnSort(false);
        tabelScroll_1.setViewportView(tabel_dashboard);
        if (tabel_dashboard.getColumnModel().getColumnCount() > 0) {
            tabel_dashboard.getColumnModel().getColumn(0).setResizable(false);
            tabel_dashboard.getColumnModel().getColumn(0).setPreferredWidth(2);
            tabel_dashboard.getColumnModel().getColumn(2).setResizable(false);
            tabel_dashboard.getColumnModel().getColumn(2).setPreferredWidth(50);
            tabel_dashboard.getColumnModel().getColumn(3).setResizable(false);
            tabel_dashboard.getColumnModel().getColumn(3).setPreferredWidth(50);
            tabel_dashboard.getColumnModel().getColumn(4).setResizable(false);
            tabel_dashboard.getColumnModel().getColumn(4).setPreferredWidth(50);
            tabel_dashboard.getColumnModel().getColumn(5).setPreferredWidth(50);
            tabel_dashboard.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        panel_table.add(tabelScroll_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 790, 360));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Data Peminjaman Buku");
        panel_table.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 780, -1));

        jPanel1.add(panel_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 790, 420));

        panel_input.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Input Peminjaman Buku");
        panel_input.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setText("Nama Peminjam");
        panel_input.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 20));

        jLabel6.setText("Nama Buku");
        panel_input.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        jLabel7.setText("Tanggal Peminjaman");
        panel_input.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 20));

        jLabel8.setText("Jumlah Hari peminjaman");
        panel_input.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        jTextField1.setText("jTextField1");
        panel_input.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 170, -1));

        jTextField2.setText("jTextField2");
        panel_input.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 170, -1));

        jTextField4.setText("jTextField4");
        panel_input.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 170, -1));
        panel_input.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 170, -1));

        jButton1.setText("Insert");
        panel_input.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jScrollPane1.setViewportView(jTable1);

        panel_input.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 17, 440, 400));

        jPanel1.add(panel_input, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 790, 420));

        panel_buku.setBackground(new java.awt.Color(255, 255, 255));
        panel_buku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelScroll_2.setBackground(new java.awt.Color(255, 255, 255));
        tabelScroll_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tabelScroll_2.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tabelScroll_2.setColumnHeaderView(null);
        tabelScroll_2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelScroll_2.setFocusable(false);

        tabel_dashboard1.setAutoCreateRowSorter(true);
        tabel_dashboard1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tabel_dashboard1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "43A87006200xxx", "Aulia", "Python", "19-07-2022", "26-07-2022", null},
                {"2", "43A87006200xxx", "Abel", "Java", "19-07-2022", "26-07-2022", "Sudah Kembali"},
                {"3", "43A87006200xxx", "Dwi", "CSS", "19-07-2022", "26-07-2022", null},
                {"4", "43A87006200xxx", "Azaria", "PHP", "19-07-2022", "26-07-2022", null}
            },
            new String [] {
                "No", "NPM", "Nama", "Buku", "Tgl Pinjam", "Tgl Kembali", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_dashboard1.setFocusable(false);
        tabel_dashboard1.setGridColor(new java.awt.Color(255, 255, 255));
        tabel_dashboard1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tabel_dashboard1.setOpaque(false);
        tabel_dashboard1.setPreferredSize(new java.awt.Dimension(400, 100));
        tabel_dashboard1.setRowHeight(25);
        tabel_dashboard1.setShowGrid(false);
        tabel_dashboard1.getTableHeader().setReorderingAllowed(false);
        tabel_dashboard1.setUpdateSelectionOnSort(false);
        tabelScroll_2.setViewportView(tabel_dashboard1);
        if (tabel_dashboard1.getColumnModel().getColumnCount() > 0) {
            tabel_dashboard1.getColumnModel().getColumn(0).setResizable(false);
            tabel_dashboard1.getColumnModel().getColumn(0).setPreferredWidth(2);
            tabel_dashboard1.getColumnModel().getColumn(2).setResizable(false);
            tabel_dashboard1.getColumnModel().getColumn(2).setPreferredWidth(50);
            tabel_dashboard1.getColumnModel().getColumn(3).setResizable(false);
            tabel_dashboard1.getColumnModel().getColumn(3).setPreferredWidth(50);
            tabel_dashboard1.getColumnModel().getColumn(4).setResizable(false);
            tabel_dashboard1.getColumnModel().getColumn(4).setPreferredWidth(50);
            tabel_dashboard1.getColumnModel().getColumn(5).setPreferredWidth(50);
            tabel_dashboard1.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        panel_buku.add(tabelScroll_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 440, 360));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Data Peminjaman Buku");
        panel_buku.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 780, -1));

        jPanel1.add(panel_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 790, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void bt_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_dashboardMouseClicked
        // TODO add your handling code here:
        panel_table.show();
        panel_input.hide();
        panel_buku.hide();
    }//GEN-LAST:event_bt_dashboardMouseClicked

    private void bt_inp_pinjamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_inp_pinjamMouseClicked
        // TODO add your handling code here:
        panel_table.hide();
        panel_input.show();
        panel_buku.hide();
    }//GEN-LAST:event_bt_inp_pinjamMouseClicked

    private void bt_inp_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_inp_bukuMouseClicked
        // TODO add your handling code here:
        panel_table.hide();
        panel_input.hide();
        panel_buku.show();
    }//GEN-LAST:event_bt_inp_bukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bt_dashboard;
    private javax.swing.JPanel bt_inp_buku;
    private javax.swing.JPanel bt_inp_pinjam;
    private javax.swing.JPanel bt_log;
    private javax.swing.JLabel image_logo;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel panel_buku;
    private javax.swing.JPanel panel_header;
    private javax.swing.JPanel panel_input;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel panel_table;
    private javax.swing.JLabel role;
    private javax.swing.JScrollPane tabelScroll_1;
    private javax.swing.JScrollPane tabelScroll_2;
    private javax.swing.JTable tabel_dashboard;
    private javax.swing.JTable tabel_dashboard1;
    private javax.swing.JLabel title;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
