/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum3;

/**
 *
 * @author ariya
 */
public class kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form kalkulaotr
     */
    public kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bil1 = new javax.swing.JTextField();
        bil2 = new javax.swing.JTextField();
        com_opr = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        field_hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kalkulator");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 20, 660, -1));

        bil1.setText("Masukan Angka");
        bil1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bil1MouseClicked(evt);
            }
        });
        jPanel1.add(bil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        bil2.setText("Masukan Angka");
        bil2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bil2MouseClicked(evt);
            }
        });
        jPanel1.add(bil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        com_opr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Operator --", "+", "-", "x", "/", "%" }));
        com_opr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_oprActionPerformed(evt);
            }
        });
        jPanel1.add(com_opr, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, -1, 30));

        field_hasil.setText("jTextField3");
        jPanel1.add(field_hasil, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bil1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bil1MouseClicked
        // TODO add your handling code here:
        bil1.setText("");
    }//GEN-LAST:event_bil1MouseClicked

    private void bil2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bil2MouseClicked
        // TODO add your handling code here:
        bil2.setText("");
    }//GEN-LAST:event_bil2MouseClicked

    private void com_oprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_oprActionPerformed
        // TODO add your handling code here:
        int tambah, kurang, kali, sisa;
        float bagi;
        if(com_opr.getSelectedItem().equals("+")){
            tambah = Integer.parseInt(bil1.getText()) + Integer.parseInt(bil2.getText());
            field_hasil.setText(String.valueOf(tambah));
        }
        if(com_opr.getSelectedItem().equals("-")){
            kurang = Integer.parseInt(bil1.getText()) - Integer.parseInt(bil2.getText());
            field_hasil.setText(String.valueOf(kurang));
        }
        if(com_opr.getSelectedItem().equals("x")){
            kali = Integer.parseInt(bil1.getText()) * Integer.parseInt(bil2.getText());
            field_hasil.setText(String.valueOf(kali));
        }
        if(com_opr.getSelectedItem().equals("/")){
            bagi = Integer.parseInt(bil1.getText()) / Integer.parseInt(bil2.getText());
            field_hasil.setText(String.valueOf(bagi));
        }
        if(com_opr.getSelectedItem().equals("%")){
            sisa = Integer.parseInt(bil1.getText()) % Integer.parseInt(bil2.getText());
            field_hasil.setText(String.valueOf(sisa));
        }
    }//GEN-LAST:event_com_oprActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bil1;
    private javax.swing.JTextField bil2;
    private javax.swing.JComboBox<String> com_opr;
    private javax.swing.JTextField field_hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
