/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import controller.koneksi;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ariya
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        removeTable(table_show);
        displayTable();
    }
    koneksi con = new koneksi();
    ResultSet rs;
    DefaultTableModel dt;
    
    int kode_brg, stock;
    
        void removeTable(JTable jt) {

        dt = (DefaultTableModel) table_show.getModel();
        int rowCount = dt.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            dt.removeRow(0);
        }
    }
        
    void displayTable() {

        removeTable(table_show);
        String sql = "SELECT * FROM trx_barang";
        System.out.println("SQL : " + sql);
        rs = con.lihatData(sql);
        DefaultTableModel dt = (DefaultTableModel) table_show.getModel();
        Object rows[];
        try {
            while (rs.next()) {
                int id = Integer.parseInt(rs.getString("id"));
                String qty = rs.getString("qty");
                String total = rs.getString("total");
                String id_barang = rs.getString("id_barang");
                String remarks = rs.getString("remarks");
                String kd_trx = rs.getString("kd_trx");
                
                
                rows = new Object[]{id, qty, total, id_barang, remarks, kd_trx};
                dt.addRow(rows);
        
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }

    }
    
//    void setTampilTable(String param) {
//
//        removeTable();
//        String sqlSelect;
//        try {
//            if (param.equals("kosong")) {
//                sqlSelect = "SELECT\n"
//                        + " trx_barang.kd_trx, \n"
//                        + " trx_barang.qty, \n"
//                        + " trx_barang.total, \n"
//                        + " barang.nama, \n"
//                        + " barang.kd_barang,\n"
//                        + " barang.harga\n"
//                        + "FROM\n"
//                        + " barang\n"
//                        + " INNER JOIN\n"
//                        + " trx_barang\n"
//                        + " ON \n"
//                        + " barang.id = trx_barang.id_barang";
//            }
//            else{
//
//                sqlSelect = "SELECT\n"
//                        + " trx_barang.kd_trx, \n"
//                        + " trx_barang.qty, \n"
//                        + " trx_barang.total, \n"
//                        + " barang.nama, \n"
//                        + " barang.kd_barang,\n"
//                        + " barang.harga\n"
//                        + "FROM\n"
//                        + " barang\n"
//                        + " INNER JOIN\n"
//                        + " trx_barang\n"
//                        + " ON \n" 
//                        + " barang.id = " 
//                        + inp_kode.inp_barang "+
//
//" and
//trx_barang.kd_trx ='"+param+"'  ";
//}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        inp_total = new javax.swing.JTextField();
        inp_kode = new javax.swing.JTextField();
        inp_barang = new javax.swing.JTextField();
        inp_harga = new javax.swing.JTextField();
        inp_qty = new javax.swing.JTextField();
        bt_popup = new javax.swing.JButton();
        bt_search = new javax.swing.JButton();
        bt_insert = new javax.swing.JButton();
        bt_update = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_show = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CV MAJU TERUS PANTANG MUNDUR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setText("Kode Trx");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setText("Barang");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel4.setText("Harga");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel5.setText("Qty");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jLabel6.setText("Total");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel1.add(inp_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 260, -1));
        jPanel1.add(inp_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 260, -1));
        jPanel1.add(inp_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 260, -1));
        jPanel1.add(inp_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 260, -1));
        jPanel1.add(inp_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 260, -1));

        bt_popup.setText("Search Pop UP");
        bt_popup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_popupActionPerformed(evt);
            }
        });
        jPanel1.add(bt_popup, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 150, 90));

        bt_search.setText("Search");
        jPanel1.add(bt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        bt_insert.setText("Insert");
        bt_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_insertActionPerformed(evt);
            }
        });
        jPanel1.add(bt_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        bt_update.setText("Update");
        jPanel1.add(bt_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        bt_delete.setText("Delete");
        jPanel1.add(bt_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        table_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "id", "qty", "total", "id_barang", "remarks", "kd_trx"
            }
        ));
        jScrollPane2.setViewportView(table_show);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 530, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_popupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_popupActionPerformed
        // TODO add your handling code here:
        popdialog popup = new popdialog(this, rootPaneCheckingEnabled);
        popup.setLocationRelativeTo(null);
        popup.setVisible(true);
        String y = popup.AmbilText();
        String sqlCari = "select * from barang where kd_barang='" + y + "'";
        try {
            rs = con.lihatData(sqlCari);
            while (rs.next()) {
                inp_barang.setText(rs.getString("nama"));
                inp_harga.setText(rs.getString("harga"));
                kode_brg = Integer.parseInt(rs.getString("id"));
                stock = Integer.parseInt(rs.getNString("qty"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_bt_popupActionPerformed

    private void bt_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_insertActionPerformed
        // TODO add your handling code here:
        try {

            int jml = Integer.parseInt(inp_qty.getText());
            int qty_new = stock - jml;
            String sqlInsert =
            "insert into trx_barang (kd_trx,qty,total,id_barang)"
                    + "values('"+inp_kode.getText()+"'  "
                    + "," + jml + ",'" + inp_total.getText() + "'," + kode_brg + ")";
            String sqlUpdate = "Update barang set qty=" + qty_new + " where id=" + kode_brg;
            con.dmlData(sqlInsert);
//update table barang
            con.dmlData(sqlUpdate);

        } catch (Exception e) {

            System.out.println("Error : " + e);

        }
//        setTampilTable("kosong");
    }//GEN-LAST:event_bt_insertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_insert;
    private javax.swing.JButton bt_popup;
    private javax.swing.JButton bt_search;
    private javax.swing.JButton bt_update;
    private javax.swing.JTextField inp_barang;
    private javax.swing.JTextField inp_harga;
    private javax.swing.JTextField inp_kode;
    private javax.swing.JTextField inp_qty;
    private javax.swing.JTextField inp_total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable table_show;
    // End of variables declaration//GEN-END:variables
}
