/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas;

import java.awt.event.KeyEvent;

/**
 *
 * @author ariya
 */
public class KHS extends javax.swing.JFrame {

    
    String jurusan;
    /**
     * Creates new form KHS
     */
    public KHS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        com_jurusan = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        field_grade = new javax.swing.JTextField();
        inpt_npm = new javax.swing.JTextField();
        inpt_nama = new javax.swing.JTextField();
        inpt_uts = new javax.swing.JTextField();
        inpt_uas = new javax.swing.JTextField();
        inpt_kehadiran = new javax.swing.JTextField();
        rb_tk = new javax.swing.JRadioButton();
        rb_ti = new javax.swing.JRadioButton();
        rb_si = new javax.swing.JRadioButton();
        rb_mi = new javax.swing.JRadioButton();
        rb_ka = new javax.swing.JRadioButton();
        jSeparator2 = new javax.swing.JSeparator();
        inpt_tugas = new javax.swing.JTextField();
        field_nilai = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tx_detail = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kartu Hasil Studi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 680, 50));

        jLabel2.setText("GRADE");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 30));

        jLabel3.setText("NPM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        jLabel4.setText("NAMA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 30));

        jLabel5.setText("JURUSAN");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel6.setText("UTS");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, 30));

        jLabel7.setText("UAS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 30));

        jLabel8.setText("KEHADIRAN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 270, 10));

        jLabel9.setText("TUGAS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 30));

        jLabel10.setText("TOTAL NILAI");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 30));

        field_grade.setText("Grade");
        jPanel1.add(field_grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 130, -1));

        inpt_npm.setText("Masukan NPM");
        inpt_npm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inpt_npmMouseClicked(evt);
            }
        });
        jPanel1.add(inpt_npm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 270, -1));

        inpt_nama.setText("Masukan Nama");
        inpt_nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpt_namaFocusGained(evt);
            }
        });
        inpt_nama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inpt_namaMouseClicked(evt);
            }
        });
        jPanel1.add(inpt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 270, -1));

        inpt_uts.setText("Nilai UTS");
        inpt_uts.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpt_utsFocusGained(evt);
            }
        });
        inpt_uts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inpt_utsMouseClicked(evt);
            }
        });
        jPanel1.add(inpt_uts, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 130, -1));

        inpt_uas.setText("Nilai UAS");
        inpt_uas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpt_uasFocusGained(evt);
            }
        });
        inpt_uas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inpt_uasMouseClicked(evt);
            }
        });
        jPanel1.add(inpt_uas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 130, -1));

        inpt_kehadiran.setText("Kehadiran");
        inpt_kehadiran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpt_kehadiranFocusGained(evt);
            }
        });
        inpt_kehadiran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inpt_kehadiranMouseClicked(evt);
            }
        });
        jPanel1.add(inpt_kehadiran, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 130, -1));

        com_jurusan.add(rb_tk);
        rb_tk.setText("Teknik Komputer");
        jPanel1.add(rb_tk, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        com_jurusan.add(rb_ti);
        rb_ti.setText("Teknik Informatika");
        jPanel1.add(rb_ti, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        com_jurusan.add(rb_si);
        rb_si.setText("Sistem Informasi");
        jPanel1.add(rb_si, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, -1, -1));

        com_jurusan.add(rb_mi);
        rb_mi.setText("Manajemen Informatika");
        jPanel1.add(rb_mi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        com_jurusan.add(rb_ka);
        rb_ka.setText("Komputerasi Akutansi");
        jPanel1.add(rb_ka, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 690, 10));

        inpt_tugas.setText("Nilai Tugas");
        inpt_tugas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inpt_tugasFocusGained(evt);
            }
        });
        inpt_tugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inpt_tugasMouseClicked(evt);
            }
        });
        jPanel1.add(inpt_tugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 130, -1));

        field_nilai.setText("Total Nilai");
        jPanel1.add(field_nilai, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 130, -1));

        jButton1.setText("Proses");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 80, -1));

        jButton2.setText("Batal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 80, -1));

        tx_detail.setColumns(20);
        tx_detail.setRows(5);
        jScrollPane1.setViewportView(tx_detail);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 370, 240));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inpt_npmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inpt_npmMouseClicked
        // TODO add your handling code here:
        inpt_npm.setText("");
    }//GEN-LAST:event_inpt_npmMouseClicked

    private void inpt_namaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inpt_namaMouseClicked
        // TODO add your handling code here:
        inpt_nama.setText("");
    }//GEN-LAST:event_inpt_namaMouseClicked

    private void inpt_utsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inpt_utsMouseClicked
        // TODO add your handling code here:
        inpt_uts.setText("");
    }//GEN-LAST:event_inpt_utsMouseClicked

    private void inpt_uasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inpt_uasMouseClicked
        // TODO add your handling code here:
        inpt_uas.setText("");
    }//GEN-LAST:event_inpt_uasMouseClicked

    private void inpt_kehadiranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inpt_kehadiranMouseClicked
        // TODO add your handling code here:
        inpt_kehadiran.setText("");
    }//GEN-LAST:event_inpt_kehadiranMouseClicked

    private void inpt_tugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inpt_tugasMouseClicked
        // TODO add your handling code here:
        inpt_tugas.setText("");
    }//GEN-LAST:event_inpt_tugasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int uts, uas, kehadiran, tugas;
        float total;
        
        uts = Integer.parseInt(inpt_uts.getText());
        uas = Integer.parseInt(inpt_uas.getText());
        kehadiran = Integer.parseInt(inpt_kehadiran.getText());
        tugas = Integer.parseInt(inpt_tugas.getText());
        
        total = (float)((kehadiran / 14) * 10) + ((tugas * 20)/100) + ((uts * 30)/100) + ((uas * 40)/100);
        
        field_nilai.setText(String.valueOf(total));
        
        if(total >= 85){
            field_grade.setText("A");
        }else if(total > 75 && total <= 85){
            field_grade.setText("B");
        }else if(total > 65 && total <= 75){
            field_grade.setText("C");
        }else if(total > 45 && total <= 65){
            field_grade.setText("D");
        } else {
            field_grade.setText("E");
        }
        
        
        
        if(rb_ti.isSelected()){
            jurusan = "Teknik Informatika";
        }
        if(rb_si.isSelected()){
            jurusan = "Sistem Informasi";
        }
        if(rb_mi.isSelected()){
            jurusan = "Manajemen Informatika";
        }
        if(rb_ka.isSelected()){
            jurusan = "Komputerisasi Akutansi";
        }
        if(rb_tk.isSelected()){
            jurusan = "Teknik Komputer";
        }
        
        
        tx_detail.setText("NPM \t: " + inpt_npm.getText() +"\n"+
                          "Nama \t: " + inpt_nama.getText() +"\n"+
                          "Jurusan \t: " + jurusan +"\n"+
                          "Nilai UTS \t: " + inpt_uts.getText() +"\n"+
                          "Nilai UAS \t: " + inpt_uas.getText() +"\n"+
                          "Kehadiran \t: " + inpt_kehadiran.getText() +"\n"+
                          "Nilai Tugas \t: " + inpt_tugas.getText() +"\n"+
                          "Nilai Akhir \t: " + field_nilai.getText() +"\n"+
                          "Grade \t: " + field_grade.getText()
                );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inpt_namaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpt_namaFocusGained
        // TODO add your handling code here:
        inpt_nama.setText("");
    }//GEN-LAST:event_inpt_namaFocusGained

    private void inpt_utsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpt_utsFocusGained
        // TODO add your handling code here:
        inpt_uts.setText("");
    }//GEN-LAST:event_inpt_utsFocusGained

    private void inpt_uasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpt_uasFocusGained
        // TODO add your handling code here:
        inpt_uas.setText("");
    }//GEN-LAST:event_inpt_uasFocusGained

    private void inpt_kehadiranFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpt_kehadiranFocusGained
        // TODO add your handling code here:
        inpt_kehadiran.setText("");
    }//GEN-LAST:event_inpt_kehadiranFocusGained

    private void inpt_tugasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inpt_tugasFocusGained
        // TODO add your handling code here:
        inpt_tugas.setText("");
    }//GEN-LAST:event_inpt_tugasFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        inpt_npm.setText("");
        inpt_nama.setText("");
        inpt_uts.setText("");
        inpt_uas.setText("");
        inpt_kehadiran.setText("");
        inpt_tugas.setText("");
        field_nilai.setText("");
        field_grade.setText("");
        tx_detail.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KHS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup com_jurusan;
    private javax.swing.JTextField field_grade;
    private javax.swing.JTextField field_nilai;
    private javax.swing.JTextField inpt_kehadiran;
    private javax.swing.JTextField inpt_nama;
    private javax.swing.JTextField inpt_npm;
    private javax.swing.JTextField inpt_tugas;
    private javax.swing.JTextField inpt_uas;
    private javax.swing.JTextField inpt_uts;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JRadioButton rb_ka;
    private javax.swing.JRadioButton rb_mi;
    private javax.swing.JRadioButton rb_si;
    private javax.swing.JRadioButton rb_ti;
    private javax.swing.JRadioButton rb_tk;
    private javax.swing.JTextArea tx_detail;
    // End of variables declaration//GEN-END:variables
}
