/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import controller.koneksi;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author ariya
 */
public class dashboard extends javax.swing.JFrame {

    ResultSet rs;
    Statement stmt;
    koneksi con = new koneksi();
    String id;

    void displaytable() {
        removeTable(table_show);
        String sql = "SELECT * FROM register";
        System.out.println("SQL : " + sql);
        rs = con.lihatData(sql);
        DefaultTableModel dt = (DefaultTableModel) table_show.getModel();
        Object rows[];
        try {
            while (rs.next()) {
                int id = Integer.parseInt(rs.getString("id"));
                String fullname = rs.getString("Fullname");
                String email = rs.getString("Email");
                String pwd = rs.getString("pwd");
                String phone = rs.getString("phone");
                String gender = rs.getString("gender");
                String birth = rs.getString("birth");

                rows = new Object[]{id, fullname, email, pwd, phone, gender, birth};
                dt.addRow(rows);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }
    }

    void disableItem() {
        inp_name.setEnabled(false);
        inp_email.setEnabled(false);
        inp_pwd.setEnabled(false);
        inp_confirmpwd.setEnabled(false);
        inp_numb.setEnabled(false);
        cb_pria.setEnabled(false);
        cb_wanita.setEnabled(false);
        inp_date.setEnabled(false);
    }

    void enableItem() {
        inp_name.setEnabled(true);
        inp_email.setEnabled(true);
        inp_pwd.setEnabled(true);
        inp_confirmpwd.setEnabled(true);
        inp_numb.setEnabled(true);
        cb_pria.setEnabled(true);
        cb_wanita.setEnabled(true);
        inp_date.setEnabled(true);
    }

    void removeTable(JTable jt) {
        DefaultTableModel dt = (DefaultTableModel) table_show.getModel();
        int rowCount = dt.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            dt.removeRow(0);
        }
    }

    void updateTables() {
        String pwd = new String(inp_pwd.getPassword());
        String confirmPwd = new String(inp_confirmpwd.getPassword());
        String ph = inp_numb.getText();
        String gender = "";
        String fullname = inp_name.getText();
        String email = inp_email.getText();
        if (cb_pria.isSelected()) {
            gender = "Male";
        }
        if (cb_wanita.isSelected()) {
            gender = "Female";
        }
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        String birth = dateFormat.format(inp_date.getDate());
        String sql = "UPDATE REGISTER SET"
                + " fullname='" + fullname + "',email='" + email + "', "
                + " pwd='" + pwd + "',confirmpwd='" + confirmPwd + "',"
                + " phone='" + ph + "',gender='" + gender + "',birth=STR_TO_DATE('" + birth + "','%d-%m-%Y')"
                + " WHERE id=" + id;
        System.out.println("SQL : " + sql);
        con.dmlData(sql);
        displaytable();
    }

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        removeTable(table_show);
        displaytable();
        bt_delete.setEnabled(false);
        bt_edit.setEnabled(false);
        disableItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender_group = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_show = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inp_name = new javax.swing.JTextField();
        inp_email = new javax.swing.JTextField();
        inp_numb = new javax.swing.JTextField();
        inp_pwd = new javax.swing.JPasswordField();
        inp_confirmpwd = new javax.swing.JPasswordField();
        cb_pria = new javax.swing.JRadioButton();
        cb_wanita = new javax.swing.JRadioButton();
        inp_date = new com.toedter.calendar.JDateChooser();
        bt_edit = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        table_show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_showMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_show);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 790, 113));

        jLabel1.setText("Date of Birth");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, 30));

        jLabel2.setText("Fullname");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 30));

        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        jLabel5.setText("Confirm Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        jLabel6.setText("Mobile Number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 30));

        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 30));
        jPanel1.add(inp_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 250, -1));
        jPanel1.add(inp_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 250, -1));
        jPanel1.add(inp_numb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 250, -1));

        inp_pwd.setText("jPasswordField1");
        jPanel1.add(inp_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 250, -1));

        inp_confirmpwd.setText("jPasswordField2");
        jPanel1.add(inp_confirmpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 250, -1));

        gender_group.add(cb_pria);
        cb_pria.setText("Pria");
        jPanel1.add(cb_pria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, -1, -1));

        gender_group.add(cb_wanita);
        cb_wanita.setText("Wanita");
        jPanel1.add(cb_wanita, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));
        jPanel1.add(inp_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 250, -1));

        bt_edit.setText("Edit");
        bt_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editActionPerformed(evt);
            }
        });
        jPanel1.add(bt_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, -1, -1));

        bt_delete.setText("Delete");
        bt_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_deleteActionPerformed(evt);
            }
        });
        jPanel1.add(bt_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DATA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 10, 820, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_showMouseClicked
        // TODO add your handling code here:
        try {
            DefaultTableModel dt = (DefaultTableModel) table_show.getModel();
            int rowId = table_show.getSelectedRow();
            id = dt.getValueAt(rowId, 0).toString();
            String sql = "select * from register where id=" + id + "";
            System.out.println("SQL : " + sql);
            rs = con.lihatData(sql);
            while (rs.next()) {
                inp_name.setText(rs.getString("fullname"));
                inp_email.setText(rs.getString("email"));
                inp_pwd.setText(rs.getString("pwd"));
                inp_confirmpwd.setText(rs.getString("pwd"));
                inp_numb.setText(rs.getString("phone"));
                String gender = rs.getString("gender");
                if (gender.equals("Male")) {
                    cb_pria.setSelected(true);
                }
                if (gender.equals("Female")) {
                    cb_wanita.setSelected(true);
                }
                Date date = (Date) new SimpleDateFormat("yyyy-MM-dd").parse((String) rs.getString("birth"));
                System.out.println("Date : " + date);
                inp_date.setDate(date);
                bt_edit.setEnabled(true);
                bt_delete.setEnabled(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : " + e);
        }
    }//GEN-LAST:event_table_showMouseClicked

    private void bt_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editActionPerformed
        // TODO add your handling code here:
        String event = bt_edit.getText();
        if (event.equals("Edit")) {
            bt_edit.setText("Update");
            enableItem();
        } else {
            JOptionPane.showMessageDialog(null, "Update");
            updateTables();
            bt_edit.setText("Edit");
            disableItem();
        }
    }//GEN-LAST:event_bt_editActionPerformed

    private void bt_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_deleteActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Yakin?");
        System.out.println("Confirm : " + confirm);
        if (confirm == 0) {
            String sql = "DELETE FROM REGISTER WHERE id=" + id;
            con.dmlData(sql);
            System.out.println("SQL : " + sql);
            displaytable();
        } else {
            bt_delete.setEnabled(false);
        }
    }//GEN-LAST:event_bt_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_delete;
    private javax.swing.JButton bt_edit;
    private javax.swing.JRadioButton cb_pria;
    private javax.swing.JRadioButton cb_wanita;
    private javax.swing.ButtonGroup gender_group;
    private javax.swing.JPasswordField inp_confirmpwd;
    private com.toedter.calendar.JDateChooser inp_date;
    private javax.swing.JTextField inp_email;
    private javax.swing.JTextField inp_name;
    private javax.swing.JTextField inp_numb;
    private javax.swing.JPasswordField inp_pwd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_show;
    // End of variables declaration//GEN-END:variables
}
