/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugas;

/**
 *
 * @author ariya
 */
public class segitiga extends javax.swing.JFrame {

    /**
     * Creates new form segitiga
     */
    
    int i, j, k, tinggi;
    public segitiga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        inpt_tinggi1 = new javax.swing.JTextField();
        bt_proses1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        hasil1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        inpt_tinggi2 = new javax.swing.JTextField();
        bt_proses2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        hasil_samakaki = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        inpt_tinggi = new javax.swing.JTextField();
        bt_proses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil_siku2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Tinggi");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        inpt_tinggi1.setText("Masukan Tinggi");
        inpt_tinggi1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inpt_tinggi1MouseClicked(evt);
            }
        });
        jPanel4.add(inpt_tinggi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 100, -1));

        bt_proses1.setText("Proses");
        bt_proses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_proses1ActionPerformed(evt);
            }
        });
        jPanel4.add(bt_proses1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        hasil1.setColumns(20);
        hasil1.setRows(5);
        jScrollPane2.setViewportView(hasil1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 370, 190));

        jTabbedPane1.addTab("Siku - Siku", jPanel4);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Tinggi");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        inpt_tinggi2.setText("Masukan Tinggi");
        inpt_tinggi2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inpt_tinggi2MouseClicked(evt);
            }
        });
        jPanel3.add(inpt_tinggi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 19, 100, -1));

        bt_proses2.setText("Proses");
        bt_proses2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_proses2ActionPerformed(evt);
            }
        });
        jPanel3.add(bt_proses2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        hasil_samakaki.setColumns(20);
        hasil_samakaki.setRows(5);
        jScrollPane3.setViewportView(hasil_samakaki);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 370, 190));

        jTabbedPane1.addTab("Sama Kaki", jPanel3);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Tinggi");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        inpt_tinggi.setText("Masukan Tinggi");
        inpt_tinggi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inpt_tinggiMouseClicked(evt);
            }
        });
        jPanel2.add(inpt_tinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 100, -1));

        bt_proses.setText("Proses");
        bt_proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_prosesActionPerformed(evt);
            }
        });
        jPanel2.add(bt_proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        hasil_siku2.setColumns(20);
        hasil_siku2.setRows(5);
        jScrollPane1.setViewportView(hasil_siku2);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 370, 190));

        jTabbedPane1.addTab("Siku - Siku", jPanel2);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Segitiga");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inpt_tinggiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inpt_tinggiMouseClicked
        // TODO add your handling code here:
        inpt_tinggi.setText("");
        
    }//GEN-LAST:event_inpt_tinggiMouseClicked

    private void bt_prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_prosesActionPerformed
        // TODO add your handling code here:
   
        tinggi = Integer.parseInt(inpt_tinggi.getText());
        hasil_siku2.setText("");
        for (i = 1 ; i <= tinggi ; i++){

            for (j = 0 ; j < i ; j++){
                hasil_siku2.append(String.valueOf("*"));
            }
            hasil_siku2.append(String.valueOf("\n"));
        }
        
            

    }//GEN-LAST:event_bt_prosesActionPerformed

    private void bt_proses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_proses1ActionPerformed
        // TODO add your handling code here:
        
        
        tinggi = Integer.parseInt(inpt_tinggi1.getText());
        hasil1.setText("");
        for (i = 1 ; i <= tinggi ; i++){
            for (j = i ; j <= tinggi ; j++){ 
                hasil1.append(String.valueOf(j));
            }

            hasil1.append(String.valueOf("\n"));
        }
        
        
    }//GEN-LAST:event_bt_proses1ActionPerformed

    private void inpt_tinggi1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inpt_tinggi1MouseClicked
        // TODO add your handling code here:
        inpt_tinggi1.setText("");
    }//GEN-LAST:event_inpt_tinggi1MouseClicked

    private void inpt_tinggi2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inpt_tinggi2MouseClicked
        // TODO add your handling code here:
        inpt_tinggi2.setText("");
    }//GEN-LAST:event_inpt_tinggi2MouseClicked

    private void bt_proses2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_proses2ActionPerformed
        // TODO add your handling code here:
        tinggi = Integer.parseInt(inpt_tinggi2.getText());
        hasil_samakaki.setText("");
        for (int i=0; i < tinggi; i++){
            for (int k=0; k < tinggi-i; k++){
                hasil_samakaki.append(String.valueOf(" "));
            }
            for (int j=0; j<i+1; j++){
                hasil_samakaki.append(String.valueOf("*"));
            }
        hasil_samakaki.append(String.valueOf("\n"));
  }
    }//GEN-LAST:event_bt_proses2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(segitiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(segitiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(segitiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(segitiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new segitiga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_proses;
    private javax.swing.JButton bt_proses1;
    private javax.swing.JButton bt_proses2;
    private javax.swing.JTextArea hasil1;
    private javax.swing.JTextArea hasil_samakaki;
    private javax.swing.JTextArea hasil_siku2;
    private javax.swing.JTextField inpt_tinggi;
    private javax.swing.JTextField inpt_tinggi1;
    private javax.swing.JTextField inpt_tinggi2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
